### ISSUE TITLE
Code background looks not good

### ISSUE THREAD

**Issue by recolic** [danpros/gridzone#1]
For style.css:183 (https://github.com/danpros/htmly-gridzone/blob/6717f8b7a09531ef71cff1c4232ae653da0cf0ae/css/style.css#L183)

```
.entry code { background: #ddd; padding: 0 3px; }
```

The background color makes code looks strange... I suggest to remove it. 

This is two screenshots, before and after removing the background color: 

![Screenshot from 2021-09-28 14-00-36](https://user-images.githubusercontent.com/19610256/135032095-6e9fa368-e7ad-4103-ab32-1fd1247a529f.png)

![Screenshot from 2021-09-28 14-00-13](https://user-images.githubusercontent.com/19610256/135032100-0c163ad5-691e-4445-a8ed-00314fa3b114.png)

**Comment by danpros** [comment]
Hi, already merge the pull request.

Thanks,
